---
title: "Model Execution and Evaluation"
author: "Sam Haynes"
date: "2023-04-03"
output: html_document
---

```{r setup}
library(tidyverse)
library(here)
library(tidybayes)
library(rstan)
library(shinystan)

perfect_real_data_set <- read_rds(here("data/output/missing_data_real_data_set.rds"))

test_enrichment <- read_csv(here("data/input/enrichment_plot_rep_sum_piv.csv")) |>
  arrange(desc(N)) |>
  separate(Sample, sep ="_", into = c("tissue_name", "sample"), extra="merge") |>
  separate(sample, sep ="_(?=[1-9]$)", into = c("cell_line_name", "rep_name")) |>
  mutate(tissue_name = factor(tissue_name),
         cell_line_name = factor(cell_line_name))

#check stan is installed
model_orig <-  stan_model(here('R/hierarchical_model_lognorm_inc_cyto.stan'))

# pass data to stan and run model
options(mc.cores = 4)
```

```{r normalise-raw-intensities-DESeq}
gene_wise_pseudo_ref <- perfect_real_data_set |>
  group_by(ProteinGroup) |>
  summarise(pseudo_ref = exp(sum(log(prot_intensity), na.rm = TRUE)/length(prot_intensity)))

sample_wise_scale_factors <- perfect_real_data_set |>
  inner_join(gene_wise_pseudo_ref) |>
  group_by(tissue_name, cell_line_name, rep_name) |>
  summarise(sample_scale_factor = median(prot_intensity / pseudo_ref, na.rm = TRUE)) |>
  ungroup()

perfect_real_data_set_normalised = perfect_real_data_set |>
  inner_join(sample_wise_scale_factors) |>
  mutate(prot_intensity = prot_intensity / sample_scale_factor)
```

```{r pre-vs-post-norm}
ggplot(perfect_real_data_set) +
  geom_boxplot(aes(y=log(prot_intensity), x= factor(cell_line))) +
  facet_wrap(~factor(rep),ncol = 1) +
  labs(title = "Unnormalised Intensity")

ggplot(perfect_real_data_set_normalised) +
  geom_boxplot(aes(y=log(prot_intensity), x= factor(cell_line))) +
  facet_wrap(~factor(rep),ncol = 1) +
  labs(title = "Normalised Intensity")
```

```{r run-stan-model-real}
n_prot <- 100

n_tissues <- 6

subset_perfect_protein_names <- perfect_real_data_set_normalised |> 
  pull(ProteinGroup) |>
  unique() |>
  sample(n_prot)

subset_perfect_tissue_names <- perfect_real_data_set_normalised |> 
  pull(tissue_name) |>
  unique() |>
  sample(n_tissues)

subset_perfect_data <- perfect_real_data_set_normalised |> 
  filter(ProteinGroup %in% subset_perfect_protein_names,
         tissue_name %in% subset_perfect_tissue_names) |>
  mutate(ProteinGroup = factor(ProteinGroup),
         protein_id =  unclass(ProteinGroup),
         tissue_name = factor(tissue_name),
         tissue =  unclass(tissue_name),
         cell_line_name = factor(cell_line_name),
         cell_line = unclass(cell_line_name))

n_cell_lines = length(unique(subset_perfect_data$cell_line_name))

n_sample = subset_perfect_data |>
  filter(protein_id == protein_id[1]) |>
  group_by(protein_id) |>
  summarise(n()) |>
  pull(`n()`)

arranged_subset_perfect_data = subset_perfect_data |>
  arrange(tissue,
          cell_line,
          rep,
          ProteinGroup)

protein_intensity_array_real_data <- array(c(arranged_subset_perfect_data |>
  mutate(prot_intensity = ifelse(is.na(prot_intensity)|prot_intensity==0,
                                 1,
                                 prot_intensity)) |>
    pull(prot_intensity) |> 
    log()),
  dim = c(n_prot,
          n_sample)) |>
  aperm(c(2,1))

subset_perfect_data_missing_data <- subset_perfect_data |>
  filter(is.na(prot_intensity))

N_missing = nrow(subset_perfect_data_missing_data)

subset_perfect_data_missing_n_cell_line <- subset_perfect_data |>
  arrange(cell_line, rep, protein_id) |> 
  group_by(cell_line,rep) |>
  summarise(n=sum(is.na(prot_intensity))) |>
  pull(n)
  
subset_perfect_data_missing_positions <- subset_perfect_data_missing_data |>
  arrange(cell_line, rep, protein_id) |>
  pull(protein_id)

fit_real <- sampling(model_orig,
                     list(num_samples = n_sample,
                          num_cell_lines = n_cell_lines,
                          num_proteins = n_prot,
                          num_tissue = n_tissues,
                          cell_line = arranged_subset_perfect_data |>
                            filter(protein_id == protein_id[1])  |>
                            pull(cell_line),
                          tissue = arranged_subset_perfect_data |>
                            group_by(cell_line) |>
                            filter(protein_id == protein_id[1],
                                   rep == 1) |> 
                            pull(tissue),
                          prot_intensity_obs = protein_intensity_array_real_data,
                          N_mis_sample = subset_perfect_data_missing_n_cell_line,
                          ii_mis = subset_perfect_data_missing_positions,
                          N_mis = N_missing),
                     iter = 1000,
                     thin = 10,
                     chains = 4)


```

```{r explore-posterior}

protein_dictionary <- subset_perfect_data |>
  group_by(ProteinGroup) |>
  summarise(protein_id = protein_id[1]) |>
  mutate(ProteinGroup = factor(ProteinGroup),
         protein_id = unclass(ProteinGroup))

cell_line_dictionary <- subset_perfect_data |>
  group_by(cell_line_name, tissue_name) |>
  summarise(tissue = tissue[1],
            cell_line = cell_line[1])

sample_dictionary <- arranged_subset_perfect_data |>
  group_by(tissue_name,cell_line_name) |>
  reframe(rep = unique(rep)) |>
  ungroup() |>
  transmute(tissue_name,
            rep,
            cell_line_name,
            sample = 1:length(cell_line_name))

fit_summary_real <- summary(fit_real)$summary |> 
  as_tibble(rownames = "parameter") |>
  transmute(parameter,
            median = `50%`)

subset_perfect_data_sorted <- arranged_subset_perfect_data |> 
  mutate(ProteinGroup = factor(ProteinGroup),
         protein_id = unclass(ProteinGroup)) |>
  group_by(ProteinGroup) |>
  mutate(sample = rep(1:n_sample))

enrichment_comparison <- subset_perfect_data_sorted |>
          group_by(tissue_name, cell_line_name,
                   rep_name,tissue, cell_line, rep, sample) |> 
          summarise(unique(rep))|>
  inner_join(test_enrichment) |>
  ungroup() |>
  inner_join(fit_real |> 
  spread_draws(enrichment[sample]) |>
  summarise_draws())
  
named_protein_results <- protein_dictionary |> 
  inner_join(fit_real |> 
  spread_draws(cyto_intensity_protein_base[tissue,protein_id]) |>
  summarise_draws()) 

ggplot(named_protein_results) + 
  geom_point(aes(x=ProteinGroup, y=log(median)))

 base_protein_results <- protein_dictionary |> 
  inner_join(fit_real |> 
  spread_draws(cyto_intensity_protein_base[tissue,protein_id]) |>
    summarise_draws()) |>
   transmute(cyto_intensity_protein_base = median,
             protein_id,
             ProteinGroup,
             tissue) |>
    inner_join(fit_real |> 
  spread_draws(chrom_intensity_protein_base[protein_id]) |>
   summarise_draws()|>
   transmute(chrom_intensity_protein_base = median,
             protein_id))
 
ggplot(base_protein_results |>
         pivot_longer(cols = c("chrom_intensity_protein_base", "cyto_intensity_protein_base"))) + 
  geom_point(aes(x=ProteinGroup, y=value, colour = name)) +
  facet_wrap(~tissue)

ggplot(test_enrichment) +
  geom_point(aes(x= C, y=N))

ggplot(enrichment_comparison) +
  geom_point(aes(x= median, y=N, shape = tissue_name, colour = tissue_name)) +
  labs(x="Enrichment") +
  geom_abline(slope = 1, intercept = 0)

ggplot(enrichment_comparison) +
  geom_point(aes(x= median, y=C)) +
  labs(x="Enrichment") +
  geom_abline(slope = 1, intercept = 0)

ggplot( tibble(gen_prot_intensity=c(apply(extract(fit_real,"gen_prot_intensity")$gen_prot_intensity,c(2,3),median))) |>
         mutate(sample = rep(1:n_sample, n_prot),
                protein_id = rep(1:n_prot, each = n_sample)) |>
         inner_join(subset_perfect_data_sorted)) +
  geom_point(aes(x = gen_prot_intensity, y = log(prot_intensity)))  +
  labs(x="gen_prot_intensity") +
  theme_bw() +
  geom_abline(slope = 1, intercept = 0)

ggplot(fit_summary_real |> 
         filter(str_detect(parameter, "chrom_intensity_sum\\[")) |>
         mutate(protein_id = rep(1:n_prot,n_cell_lines),
                cell_line = rep(1:n_cell_lines,each = n_prot),
                                chrom = median) |>
         inner_join(cell_line_dictionary) |>
         inner_join(fit_summary_real |> 
                      filter(str_detect(parameter, "cyto_intensity_protein_base")) |>
                      transmute(protein_id = rep(1:n_prot, n_tissues),
                                tissue = rep(1:n_tissues, each = n_prot),
                                cyto = median)) |>
         filter(protein_id < 100)) +
  geom_point(aes(chrom, y=cyto, colour = factor(protein_id)))  +
  geom_abline(slope = 1, intercept = 0)+
  coord_equal()
```

```{r compare-to-hyperlopit}
protein_localisation_dataset <- read_tsv(here("data/input/annot_hyperlopit.tsv")) |>
  mutate(final.assignment = as.factor(final.assignment))

compare_localisation <- protein_dictionary |> 
  inner_join(fit_real |> 
  spread_draws(chrom_intensity_sum[cell_line,protein_id]) |>
  summarise_draws()|>
  transmute(cell_line,
            protein_id,
            chrom_intensity_sum = median)) |>
         inner_join(cell_line_dictionary) |>  
  inner_join(fit_real |> 
  spread_draws(cyto_intensity_protein_base[protein_id, tissue]) |>
  summarise_draws() |>
  transmute(protein_id,
            tissue,
            cyto_intensity_protein_base = median)) |> 
  mutate(Uniprot = ifelse(str_detect(ProteinGroup, ";"),
                               str_extract(ProteinGroup, "[A-Z0-9-]+(?=;)"),
                               as.character(ProteinGroup))) |>
  inner_join(protein_localisation_dataset) |>
  transmute(Uniprot,
            final.assignment,
            cyto_intensity_protein_base,
            cell_line,
            tissue,
            chrom_intensity_sum) |>
  group_by(Uniprot,
            cell_line) |>
  summarise(cyto_intensity_protein_base = cyto_intensity_protein_base[1:2],
            final.assignment = final.assignment[1:2],
            chrom_intensity_sum = chrom_intensity_sum[1:2])

compare_localisation_global <- protein_dictionary |> 
  inner_join(fit_real |> 
  spread_draws(chrom_intensity_protein_base[protein_id]) |>
  summarise_draws() |>
    transmute(protein_id,
              chrom_intensity_protein_base = median)) |> 
  inner_join(fit_real |> 
               spread_draws(cyto_intensity_protein_base[tissue,protein_id])|>
  summarise_draws() |>
    transmute(protein_id,
              tissue,
              cyto_intensity_protein_base = median)) |>
  mutate(Uniprot = ifelse(str_detect(ProteinGroup, ";"),
                               str_extract(ProteinGroup, "[A-Z0-9-]+(?=;)"),
                               as.character(ProteinGroup))) |>
  inner_join(protein_localisation_dataset) |>
  transmute(Uniprot,
            tissue,
            final.assignment,
            cyto_intensity_protein_base,
            chrom_intensity_protein_base) |>
  group_by(Uniprot) |>
  summarise(cyto_intensity_protein_base = cyto_intensity_protein_base[1:n_tissues],
            final.assignment = final.assignment[1:n_tissues],
            chrom_intensity_protein_base = chrom_intensity_protein_base[1:n_tissues],
            tissue = tissue[1:n_tissues])

ggplot(compare_localisation_global) +
  geom_boxplot(aes(x = final.assignment, y=chrom_intensity_protein_base - cyto_intensity_protein_base)) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90),
        axis.title.x = element_blank(),
        panel.grid.minor.y = element_blank()) +
  facet_wrap(~tissue)

ggplot(compare_localisation |>
         filter(cell_line %in% 1:6)) +
  geom_boxplot(aes(x = final.assignment, y=chrom_intensity_sum - cyto_intensity_protein_base)) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90),
        axis.title.x = element_blank(),
        panel.grid.minor.y = element_blank()) +
  facet_wrap(~cell_line)
```

```{r explore_hyperparameters}
sigma_samples<- spread_draws(fit_real, sigma)

ggplot(sigma_samples |>
  transmute(sigma,
            prior = rexp(200, 1)) |>
    pivot_longer(cols = c("sigma","prior"), names_to = "source", values_to = "values")) +
  geom_histogram(aes(x=values, fill = source), alpha = 0.7) +
  theme_minimal()

sigma_cyto_samples<- spread_draws(fit_real, sigma_cyto[tissue]) |>
  summarise_draws()

ggplot(sigma_cyto_samples |>
         ungroup() |>
  transmute(sigma_cyto = median,
            prior = rexp(10, 1)) |>
    pivot_longer(cols = c("sigma_cyto","prior"), names_to = "source", values_to = "values")) +
  geom_histogram(aes(x=values, fill = source), alpha = 0.7) +
  theme_minimal()

cyto_intensity_protein_samples <- spread_draws(fit_real, cyto_intensity_protein[protein]) |>
  summarise_draws()

ggplot(cyto_intensity_protein_samples |>
         ungroup() |>
  transmute(cyto_intensity_protein =median,
            prior = rnorm(100, 18,2)) |>
    pivot_longer(cols = c("cyto_intensity_protein","prior"), names_to = "source", values_to = "values")) +
  geom_histogram(aes(x=values, fill = source), alpha = 0.7) +
  theme_minimal()

enrichment_samples <- spread_draws(fit_real, enrichment[sample]) |>
  summarise_draws()

ggplot(enrichment_samples |>
         ungroup() |>
  transmute(enrichment = median,
            prior = rnorm(108, 0.4,0.2)) |>
    pivot_longer(cols = c("enrichment","prior"), names_to = "source", values_to = "values")) +
  geom_histogram(aes(x=values, fill = source), alpha = 0.7) +
  theme_minimal()

cyto_chrom_ratio_sample <- spread_draws(fit_real, cyto_chrom_ratio[protein]) |>
  summarise_draws()

ggplot(cyto_chrom_ratio_sample |>
         ungroup() |>
  transmute(cyto_chrom_ratio = median,
            prior = rnorm(100, 1, 0.4)) |>
    pivot_longer(cols = c("cyto_chrom_ratio","prior"), names_to = "source", values_to = "values")) +
  geom_histogram(aes(x=values, fill = source), alpha = 0.7) +
  theme_minimal()+
  lims(x = c(0,3))

mu_cyto_sample <- spread_draws(fit_real, mu_cyto[tissue,protein]) |>
  summarise_draws()

ggplot(mu_cyto_sample |>
         ungroup() |>
  transmute(mu_cyto =median,
            prior = rnorm(1000, 0, 0.5)) |>
    pivot_longer(cols = c("mu_cyto","prior"), names_to = "source", values_to = "values")) +
  geom_histogram(aes(x=values, fill = source), alpha = 0.7) +
  theme_minimal()
```

```{r run-stanfit, eval=FALSE}
launch_shinystan(fit_real)
```

```{r}
ggplot(fit_real |>
  spread_draws(chrom_intensity_sum[cell_line,protein_id]) |>
  filter(protein_id == 3) |>
  inner_join(fit_real |>
  spread_draws(cyto_intensity_sum[cell_line,protein_id]))) +
  geom_point(aes(x=chrom_intensity_sum,y=cyto_intensity_sum,colour=factor(cell_line)))
```

```{r calc_nuc_frac, eval=FALSE}
cyto_chrom_ratio_pred <- fit_real |>
                   spread_draws(cyto_chrom_ratio[protein_id])|>
  group_by(protein_id,.chain) |>
  transmute(.draw,
            cyto_chrom_ratio = sample(cyto_chrom_ratio, length(cyto_chrom_ratio)))

cell_line_upper <- fit_real |>
                   spread_draws(chrom_intensity_protein[protein_id])|>
  group_by(protein_id,.chain) |>
  transmute(.draw,
            chrom_intensity_protein = sample(chrom_intensity_protein, length(chrom_intensity_protein)))

cell_line_n_min_1 <- fit_real |>
                   spread_draws(chrom_intensity_cell_line_n_min_1[cell_line,protein_id]) |>
  group_by(cell_line,protein_id,.chain) |>
  transmute(.draw,
            chrom_intensity_cell_line_n_min_1 = sample(chrom_intensity_cell_line_n_min_1, length(chrom_intensity_cell_line_n_min_1)))

nucl_cyto_intensity <- cell_line_n_min_1 |>
  inner_join(cell_line_upper) |>
  transmute(cell_line,
            protein_id,
            .chain,
            .draw,
            cyto_intensity = chrom_intensity_cell_line_n_min_1 + chrom_intensity_protein) |>
  bind_rows(cell_line_upper |>
              transmute(cell_line = 54,
                     protein_id,
                     .chain,
                     .draw,
                     cyto_intensity = chrom_intensity_protein)) |>
  ungroup() |>
  inner_join(cyto_chrom_ratio_pred,
             relationship = "many-to-one",
             by=c("protein_id", ".chain", ".draw")) |>
  mutate(chrom_intensity = cyto_intensity + log(cyto_chrom_ratio)) |>
  inner_join(protein_dictionary) |>
  inner_join(cell_line_dictionary)
```

```{r output-results, eval=FALSE}
write_csv(file = here("data/output/predicted_enrichment.csv"), enrichment_comparison |>
            transmute(tissue_name,
                      cell_line_name,
                      rep,
                      C,
                      N,
                      S,
                      M,
                      predicted_enrichment = median))

write_csv(file = here("data/output/predicted_intensity_1000_gene.csv"),
          protein_dictionary |> 
            inner_join(fit_real |>
                         spread_draws(prot_intensity_est[sample,protein_id])) |>
            inner_join(sample_dictionary))

write_csv(file = here("data/output/predicted_ratio_1000_gene.csv"),
          protein_dictionary |> 
            inner_join(fit_real |>
                         spread_draws(cyto_chrom_ratio[protein_id])))

write_csv(file = here("data/output/predicted_chrom_cyto_intensity_1000_gene.csv"),
          nucl_cyto_intensity)

#saveRDS(fit_real, file = here("data/output/trained_sub_real_data_model.rds"))

#saveRDS(subset_perfect_data, file = here("data/output/subset_perfect_data.rds"))
```