---
title: "Model Execution and Evaluation"
author: "Sam Haynes"
date: "2023-04-03"
output: html_document
---

```{r setup}
library(tidyverse)
library(here)
library(tidybayes)
library(rstan)
library(shinystan)

sam_test_dataset_simple <- read_csv(here("data/output/simulated_dataset.csv"))

n_reps <-  sam_test_dataset_simple$rep |> max()

n_prot <-  sam_test_dataset_simple$protein_id |> max()

n_tissue <- 1

n_cell_lines <-  sam_test_dataset_simple$cell_line |> max()

#check stan is installed
model_orig <-  stan_model(here('R/simulated_hierarchical_model.stan'))

# pass data to stan and run model
options(mc.cores = 4)
```

```{r run-stan-model-simulated}

sam_test_dataset_simple_partial_data <- sam_test_dataset_simple |>
  sample_frac(0.99)

sam_test_dataset_simple_missing_data <- sam_test_dataset_simple |>
  filter(!str_c(protein_id,rep,cell_line, sep = "_") %in%
           str_c(sam_test_dataset_simple_partial_data$protein_id,
                 sam_test_dataset_simple_partial_data$rep,
                 sam_test_dataset_simple_partial_data$cell_line, sep = "_"))
 
matrix_input = sam_test_dataset_simple_partial_data |>
  bind_rows(sam_test_dataset_simple_missing_data |>
              mutate(prot_int = 0)) |>
  arrange(cell_line, rep, protein_id) |>
  pull(prot_int) |>
  array(dim = c(n_prot,
                n_reps*n_cell_lines)) |>
  aperm(c(2,1))

N_missing = nrow(sam_test_dataset_simple_missing_data)

sam_test_dataset_simple_missing_n_cell_line <- sam_test_dataset_simple_partial_data |>
  bind_rows(sam_test_dataset_simple_missing_data |>
              mutate(prot_int = NA)) |>
  arrange(cell_line, rep, protein_id) |> 
  group_by(cell_line,rep) |>
  summarise(n=sum(is.na(prot_int))) |>
  pull(n)

sam_test_dataset_simple_missing_positions <- sam_test_dataset_simple_missing_data |>
  arrange(cell_line, rep, protein_id) |>
  pull(protein_id)
  
fit3 <- sampling(model_orig, list(num_cell_lines = n_cell_lines,
                                  num_samples = n_reps*n_cell_lines,
                                  num_proteins = n_prot,
                                  cell_line = rep(1:n_cell_lines, each = n_reps),
                                  num_tissue = n_tissue,
                                  tissue = rep(1, n_cell_lines),
                                  prot_intensity_obs = matrix_input,
                                  N_mis_sample = sam_test_dataset_simple_missing_n_cell_line,
                                  ii_mis = sam_test_dataset_simple_missing_positions,
                                  N_mis = N_missing), 
                 iter = 2000, chains = 4
                 # , init = init_fun
)

# save(fit3, file=here("data/output/simulated_data_model_result"))
```

```{r check-input-missing-values, eval=FALSE}
x=0
for(s in 1:length(sam_test_dataset_simple_missing_n_cell_line)){
  if(sam_test_dataset_simple_missing_n_cell_line[s] > 0){
    x = x + sam_test_dataset_simple_missing_n_cell_line[s]
    print(matrix_input[s, sam_test_dataset_simple_missing_positions[x]])
    print(s)
    print(x)
  }
}
```

```{r explore-posterior-cell-line, eval=TRUE}
fit_summary <- summary(fit3)$summary |> 
  as_tibble(rownames = "parameter") |>
  transmute(parameter,
            median = `50%`)


ggplot(fit_summary |> 
         filter(str_detect(parameter, "enrichment\\[")) |>
         mutate(rep = rep(1:n_reps, n_cell_lines),
                cell_line = rep(1:n_cell_lines, each = n_reps)) |>
         inner_join(sam_test_dataset_simple |> 
                      group_by(rep,cell_line) |> 
                      summarise(enrichment = unique(enrichment)))) +
  geom_point(aes(x= median, y=enrichment)) +
  labs(x="Enrichment") +
  theme_bw() +
  geom_abline(slope = 1, intercept = 0) +
  coord_equal()

ggplot(fit_summary |> 
         filter(str_detect(parameter, "cyto_chrom_diff_protein\\[")) |>
         mutate(protein_id = rep(1:n_prot,n_cell_lines-1),
                cell_line = rep(1:(n_cell_lines-1),each = n_prot)) |>
         inner_join(sam_test_dataset_simple |> 
                      group_by(protein_id,
                               cell_line) |> 
                      summarise(Pr_chrom = mean(change_abund)))) +
  geom_point(aes(median, y=Pr_chrom))  +
  labs(x="Cyto Vs Chrom Diff") +
  geom_abline(slope = 1, intercept = 0) +
  coord_equal()


ggplot(fit3 |> 
         extract("gen_prot_intensity") |>
         as_tibble() |>
         summarise(gen_prot_intensity=c(apply(gen_prot_intensity,c(2,3),median))) |>
         mutate(rep = rep(1:n_reps, n_cell_lines * n_prot),
               cell_line = rep(rep(1:n_cell_lines, each = n_reps), n_prot),
                protein_id = rep(1:n_prot, each = n_reps * n_cell_lines)) |>
         inner_join(sam_test_dataset_simple)) +
  geom_point(aes(x = gen_prot_intensity, y = prot_int, colour = protein_id))  +
  labs(x="gen_prot_intensity") +
  theme_bw() +
  geom_abline(slope = 1, intercept = 0)  +
  coord_equal()

ggplot(fit_summary |> 
         filter(str_detect(parameter, "cyto_intensity_sum")) |>
         mutate(protein_id = rep(1:n_prot,n_cell_lines),
                cell_line = rep(1:n_cell_lines,each = n_prot)) |>
         inner_join(sam_test_dataset_simple |> 
                      group_by(protein_id,
                               cell_line) |>
                      summarise(Pr_cyto = mean(Pr_cyto)))) +
  geom_point(aes(median, y=Pr_cyto))  +
  labs(x="cyto_intensity") +
  geom_abline(slope = 1, intercept = 0)+
  coord_equal()

ggplot(fit_summary |> 
         filter(str_detect(parameter, "chrom_intensity_sum")) |>
         mutate(protein_id = rep(1:n_prot,n_cell_lines),
                cell_line = rep(1:n_cell_lines,each = n_prot)) |>
         inner_join(sam_test_dataset_simple |> 
                      group_by(protein_id,
                               cell_line) |> 
                      summarise(Pr_nucl = mean(Pr_nucl)))) +
  geom_point(aes(median, y=Pr_nucl))  +
  labs(x="chrom_intensity") +
  geom_abline(slope = 1, intercept = 0)+
  coord_equal()

ggplot(fit_summary |> 
         filter(str_detect(parameter, "chrom_intensity_sum")) |>
         mutate(protein_id = rep(1:n_prot,n_cell_lines),
                cell_line = rep(1:n_cell_lines,each = n_prot),
                                chrom = median) |>
         inner_join(fit_summary |> 
                      filter(str_detect(parameter, "cyto_intensity_sum")) |>
                      transmute(protein_id = rep(1:n_prot,n_cell_lines),
                                cell_line = rep(1:n_cell_lines,each = n_prot),
                                cyto = median)) |>
         filter(protein_id < 20)) +
  geom_point(aes(chrom, y=cyto, colour = factor(protein_id)))  +
  geom_abline(slope = 1, intercept = 0)+
  coord_equal()

```

```{r explore-missing-value-posterior}
missing_proteins_cell_lines <- sam_test_dataset_simple_missing_data |>
  transmute(missing_proteins = str_c(protein_id,cell_line,sep="_"))

posterior_missing_data <- sam_test_dataset_simple_missing_data |> 
  mutate(inferred_median = fit_summary |> 
           filter(str_detect(parameter, "prot_intensity_mis\\[")) |> 
           pull(median))

missing_value_posterior <- sam_test_dataset_simple |>
  filter(str_c(protein_id,cell_line,sep="_") %in% missing_proteins_cell_lines$missing_proteins) |>
  inner_join(posterior_missing_data |>
               dplyr::rename(rep_post = rep),
             by = c("protein_id", "cell_line"))

ggplot(missing_value_posterior |>
         filter(rep != rep_post)) +
  geom_point(aes(x=inferred_median,y=prot_int.x, colour = factor(rep))) +
  theme_bw() +
  coord_equal() +
  geom_abline(intercept = 0, slope = 1)
```

```{r explore-posterior-no-cell-line, eval=FALSE}
fit_summary <- summary(fit3)$summary |> 
  as_tibble(rownames = "parameter") |>
  transmute(parameter,
            median = `50%`)


ggplot(fit_summary |> 
         filter(str_detect(parameter, "enrichment\\[")) |>
         mutate(rep = rep(1:n_reps, n_cell_lines),
                cell_line = rep(1:n_cell_lines, each = n_reps)) |>
         inner_join(sam_test_dataset_simple |> 
                      group_by(rep,cell_line) |> 
                      summarise(enrichment = unique(enrichment)))) +
  geom_point(aes(x= median, y=enrichment)) +
  labs(x="Enrichment") +
  theme_bw() +
  geom_abline(slope = 1, intercept = 0) +
  coord_equal()

ggplot(fit_summary |> 
         filter(str_detect(parameter, "chrom_intensity_protein")) |>
         mutate(protein_id = 1:n_prot) |>
         inner_join(sam_test_dataset_simple |> 
                      group_by(protein_id) |> 
                      summarise(Pr_chrom = mean(Pr_nucl)))) +
  geom_point(aes(median, y=Pr_chrom))  +
  labs(x="chrom_intensity") +
  geom_abline(slope = 1, intercept = 0)+
  coord_equal()

ggplot(fit_summary |> 
         filter(str_detect(parameter, "chrom_intensity_protein")) |>
         mutate(protein_id = 1:n_prot) |>
         inner_join(sam_test_dataset_simple |> 
                      group_by(protein_id) |> 
                      summarise(Pr_cyto = mean(Pr_cyto)))) +
  geom_point(aes(median, y=Pr_cyto))  +
  labs(x="chrom_intensity") +
  geom_abline(slope = 1, intercept = 0)+
  coord_equal()

ggplot(fit_summary |> 
         filter(str_detect(parameter, "cyto_intensity_protein")) |>
         transmute(protein_id = 1:n_prot,
                   cyto = median) |>
         inner_join(fit_summary |> 
                      filter(str_detect(parameter, "chrom_intensity_protein")) |>
                      transmute(protein_id = 1:n_prot,
                                chrom = median))|>
         inner_join(sam_test_dataset_simple |> 
                      group_by(protein_id) |> 
                      summarise(total = mean(total)))) +
  geom_point(aes(chrom, y=cyto, colour = total)) +
  geom_abline(slope = 1, intercept = 0)+
  coord_equal()

ggplot(fit_summary |> 
         filter(str_detect(parameter, "cyto_intensity_protein_")) |>
         mutate(protein_id = 1:n_prot) |>
         inner_join(sam_test_dataset_simple |> 
                      group_by(protein_id) |> 
                      summarise(Pr_cyto = mean(Pr_cyto)))) +
  geom_point(aes(median, y=Pr_cyto))  +
  labs(x="cyto_intensity") +
  geom_abline(slope = 1, intercept = 0)+
  coord_equal()

ggplot(fit_summary |> 
         filter(str_detect(parameter, "cyto_intensity_protein")) |>
         mutate(protein_id = 1:n_prot) |>
         inner_join(sam_test_dataset_simple |> 
                      group_by(protein_id) |> 
                      summarise(Pr_nucl = mean(Pr_nucl)))) +
  geom_point(aes(median, y=Pr_nucl))  +
  labs(x="cyto_intensity") +
  geom_abline(slope = 1, intercept = 0)+
  coord_equal()

ggplot(fit_summary |> 
         filter(str_detect(parameter, "cyto_chrom_intensity_diff")) |>
         mutate(protein_id = rep(1:n_prot,n_cell_lines),
                cell_line = rep(1:n_cell_lines,n_prot)) |>
         inner_join(sam_test_dataset_simple |> 
                      group_by(protein_id,
                               cell_line) |> 
                      summarise(Diff = mean(change_abund)))) +
  geom_point(aes(median, y=Diff))  +
  labs(x="Pred Difference") +
  geom_abline(slope = 1, intercept = 0)+
  coord_equal()

ggplot(fit_summary |> 
         filter(str_detect(parameter, "cyto_chrom_intensity_diff")) |>
         mutate(protein_id = rep(1:n_prot,n_cell_lines),
                cell_line = rep(1:n_cell_lines,n_prot)) |>
         inner_join(fit_summary |> 
         filter(str_detect(parameter, "chrom_intensity_protein")) |>
         transmute(protein_id = 1:n_prot,
                   chrom = median))) +
  geom_point(aes(median, y=chrom))  +
  labs(x="Pred Difference") +
  geom_abline(slope = 1, intercept = 0)+
  coord_equal()

ggplot(fit3 |> 
         extract("gen_prot_intensity") |>
         as_tibble() |>
         summarise(gen_prot_intensity=c(apply(gen_prot_intensity,c(2,3),median))) |>
         mutate(rep = rep(1:n_reps, n_cell_lines * n_prot),
               cell_line = rep(rep(1:n_cell_lines, each = n_reps), n_prot),
                protein_id = rep(1:n_prot, each = n_reps * n_cell_lines)) |>
         inner_join(sam_test_dataset_simple)) +
  geom_point(aes(x = gen_prot_intensity, y = prot_int, colour = protein_id))  +
  labs(x="gen_prot_intensity") +
  theme_bw() +
  geom_abline(slope = 1, intercept = 0) +
  coord_equal()

```

```{r explore-priors, eval=FALSE}
fit_summary |> 
  filter(str_detect(parameter, "enrichment")) |>
  pull(median) |>
  hist()

fit_summary |> 
  filter(str_detect(parameter, "sigma_total_intensity")) |>
  pull(median) |>
  hist()

fit_summary |> 
  filter(str_detect(parameter, "cyto_intensity_protein")) |>
  pull(median) |>
  hist()

fit_summary |> 
  filter(str_detect(parameter, "chrom_intensity_protein")) |>
  pull(median) |>
  hist()


```

```{r}
predicted_ratios <- fit_summary |> 
  filter(str_detect(parameter, "chrom_intensity_sum")) |>
  mutate(protein_id = rep(1:n_prot,n_cell_lines),
         cell_line = rep(1:n_cell_lines,each = n_prot),
         chrom = median) |>
  inner_join(fit_summary |> 
               filter(str_detect(parameter, "cyto_intensity_sum")) |>
               transmute(protein_id = rep(1:n_prot,n_cell_lines),
                         cell_line = rep(1:n_cell_lines,each = n_prot),
                         cyto = median)) |>
  mutate(ratio = chrom-cyto)

ggplot(predicted_ratios |>
  inner_join(sam_test_dataset_simple |>
               filter(rep == 1) |>
               transmute(protein_id,
                      cell_line,
                      simulated_change = Pr_cyto - Pr_nucl))) +
  geom_point(aes(x = ratio, y= -simulated_change, colour = cell_line)) +
  geom_abline(slope = 1, intercept = 0) +
  coord_equal()
```

```{r run-stanfit, eval=FALSE}
launch_shinystan(fit3)
```